# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Architecture diagram upload
      uses: fjogeleit/http-request-action@v1.10.0
      with:
        url: 'https://anypoint.mulesoft.com/exchange/api/v2/assets/e3791168-3b1f-42be-885f-f961c1db6a86/sample/1.0.0/portal/draft/pages/architecture documents'
        method: 'PUT'
        bearerToken: '12f47193-abd9-4983-bf46-2e8a5a4ca40d'
        customHeaders: '{"Content-Type": "text/markdown"}'
        file: "architecture.md"
    - name: Technical details upload
      uses: fjogeleit/http-request-action@v1.10.0
      with:
        url: 'https://anypoint.mulesoft.com/exchange/api/v2/assets/e3791168-3b1f-42be-885f-f961c1db6a86/sample/1.0.0/portal/draft/pages/technical documents'
        method: 'PUT'
        bearerToken: '12f47193-abd9-4983-bf46-2e8a5a4ca40d'
        customHeaders: '{"Content-Type": "text/markdown"}'
        file: "technicaldetails.md"
    - name: API policies upload
      uses: fjogeleit/http-request-action@v1.10.0
      with:
        url: 'https://anypoint.mulesoft.com/exchange/api/v2/assets/e3791168-3b1f-42be-885f-f961c1db6a86/sample/1.0.0/portal/draft/pages/API policies'
        method: 'PUT'
        bearerToken: '12f47193-abd9-4983-bf46-2e8a5a4ca40d'
        customHeaders: '{"Content-Type": "text/markdown"}'
        file: "apipolicies.md"
    - name: Testing Model upload
      uses: fjogeleit/http-request-action@v1.10.0
      with:
        url: 'https://anypoint.mulesoft.com/exchange/api/v2/assets/e3791168-3b1f-42be-885f-f961c1db6a86/sample/1.0.0/portal/draft/pages/Testing Model'
        method: 'PUT'
        bearerToken: '12f47193-abd9-4983-bf46-2e8a5a4ca40d'
        customHeaders: '{"Content-Type": "text/markdown"}'
        file: "testingmodel.md"
    - name: Publish to exchange
      uses: fjogeleit/http-request-action@v1.10.0
      with:
        url: 'https://anypoint.mulesoft.com/exchange/api/v2/assets/e3791168-3b1f-42be-885f-f961c1db6a86/sample/1.0.0/portal'
        method: 'PATCH'
        bearerToken: '12f47193-abd9-4983-bf46-2e8a5a4ca40d'
